services:
  DistributedDBs:
    container_name: distributeddbs
    build:
      context: .
      dockerfile: DistributedDBs/Dockerfile
    depends_on: 
    - mongo
    - mssql
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: M6RT!+whfc4!PNk
    volumes:
      - mongo-data:/data/db

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M6RT!+whfc4!PNk
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mongo-data:
  mssql-data:
